/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/quizzes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Quizzes_ListQuiz"];
        put?: never;
        post: operations["Quizzes_CreateQuiz"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quizzes/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Quizzes_SearchQuiz"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quizzes/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["Quizzes_GetQuiz"];
        put?: never;
        post?: never;
        delete: operations["Quizzes_DeleteQuiz"];
        options?: never;
        head?: never;
        patch: operations["Quizzes_UpdateQuiz"];
        trace?: never;
    };
    "/quizzes/{quizId}/questions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["QuizQuestions_ListQuestion"];
        put?: never;
        post: operations["QuizQuestions_AddQuestion"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quizzes/{quizId}/questions/{questionId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["QuizQuestions_DeleteQuestion"];
        options?: never;
        head?: never;
        patch: operations["QuizQuestions_UpdateQuestion"];
        trace?: never;
    };
    "/quizzes/{quizId}/questions/{questionId}/answers/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["QuizAnswers_ValidateQuestionAnswers"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quizzes/{quizId}/questions/{questionId}/choices": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["QuizAnswers_ListChoice"];
        put?: never;
        post: operations["QuizAnswers_CreateChoice"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/quizzes/{quizId}/questions/{questionId}/choices/{choiceId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["QuizAnswers_DeleteChoice"];
        options?: never;
        head?: never;
        patch: operations["QuizAnswers_UpdateChoice"];
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "quiz.v1.AddQuestionRequest": {
            quizId?: string;
            question?: string;
            /** Format: enum */
            difficulty?: number;
            /** Format: float */
            order?: number;
        };
        "quiz.v1.AddQuestionResponse": {
            quizId?: string;
            question?: components["schemas"]["quiz.v1.QuizQuestion"];
        };
        "quiz.v1.AnswerResult": {
            answer?: string;
            isCorrect?: boolean;
        };
        "quiz.v1.Audit": {
            createdBy?: string;
            updatedBy?: string;
            deletedBy?: string;
            createdAt?: string;
            updatedAt?: string;
            deletedAt?: string;
        };
        "quiz.v1.Choice": {
            id?: string;
            choice?: string;
            /** Format: float */
            order?: number;
            isCorrect?: boolean;
        };
        "quiz.v1.CreateChoiceRequest": {
            quizId?: string;
            questionId?: string;
            choice?: string;
            /** Format: float */
            order?: number;
            isCorrect?: boolean;
        };
        "quiz.v1.CreateChoiceResponse": {
            quizId?: string;
            questionId?: string;
            choice?: components["schemas"]["quiz.v1.Choice"];
        };
        "quiz.v1.CreateQuizRequest": {
            title?: string;
            description?: string;
            duration?: string;
            thumbnail?: string;
            cover?: string;
            category?: string;
            tags?: string[];
            metadata?: {
                [key: string]: string;
            };
        };
        "quiz.v1.CreateQuizResponse": {
            quiz?: components["schemas"]["quiz.v1.Quiz"];
        };
        "quiz.v1.DeleteChoiceResponse": {
            quizId?: string;
        };
        "quiz.v1.DeleteQuestionResponse": {
            quizId?: string;
        };
        "quiz.v1.DeleteQuizResponse": {
            id?: string;
        };
        "quiz.v1.GetQuizResponse": {
            quiz?: components["schemas"]["quiz.v1.Quiz"];
        };
        "quiz.v1.ListChoiceResponse": {
            choices?: components["schemas"]["quiz.v1.Choice"][];
        };
        "quiz.v1.ListQuestionResponse": {
            questions?: components["schemas"]["quiz.v1.QuizQuestion"][];
        };
        "quiz.v1.ListQuizResponse": {
            quizzes?: components["schemas"]["quiz.v1.Quiz"][];
            pagination?: components["schemas"]["quiz.v1.Pagination"];
        };
        "quiz.v1.Pagination": {
            /** Format: int32 */
            page?: number;
            /** Format: int32 */
            pageSize?: number;
        };
        "quiz.v1.Quiz": {
            id?: string;
            userId?: string;
            title?: string;
            description?: string;
            duration?: string;
            /** Format: enum */
            difficulty?: number;
            thumbnail?: string;
            cover?: string;
            category?: string;
            tags?: string[];
            metadata?: {
                [key: string]: string;
            };
            audit?: components["schemas"]["quiz.v1.Audit"];
        };
        "quiz.v1.QuizQuestion": {
            id?: string;
            question?: string;
            answers?: string[];
            /** Format: uint32 */
            correctAnswer?: number;
            /** Format: enum */
            difficulty?: number;
            audit?: components["schemas"]["quiz.v1.Audit"];
        };
        "quiz.v1.SearchQuizResponse": {
            quizzes?: components["schemas"]["quiz.v1.Quiz"][];
            pagination?: components["schemas"]["quiz.v1.Pagination"];
        };
        "quiz.v1.UpdateChoiceRequest": {
            quizId?: string;
            questionId?: string;
            choiceId?: string;
            choice?: string;
            /** Format: float */
            order?: number;
            isCorrect?: boolean;
        };
        "quiz.v1.UpdateChoiceResponse": {
            quizId?: string;
            questionId?: string;
            choiceId?: string;
            choice?: components["schemas"]["quiz.v1.Choice"];
        };
        "quiz.v1.UpdateQuestionRequest": {
            quizId?: string;
            questionId?: string;
            question?: components["schemas"]["quiz.v1.QuizQuestion"];
        };
        "quiz.v1.UpdateQuestionResponse": {
            quizId?: string;
            questionId?: string;
            question?: components["schemas"]["quiz.v1.QuizQuestion"];
        };
        "quiz.v1.UpdateQuizRequest": {
            id?: string;
            title?: string;
            description?: string;
            duration?: string;
            thumbnail?: string;
            cover?: string;
            category?: string;
            tags?: string[];
            metadata?: {
                [key: string]: string;
            };
        };
        "quiz.v1.UpdateQuizResponse": {
            quiz?: components["schemas"]["quiz.v1.Quiz"];
        };
        "quiz.v1.ValidateQuestionAnswersRequest": {
            quizId?: string;
            questionId?: string;
            answers?: string[];
        };
        "quiz.v1.ValidateQuestionAnswersResponse": {
            results?: components["schemas"]["quiz.v1.AnswerResult"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    Quizzes_ListQuiz: {
        parameters: {
            query?: {
                "pagination.page"?: number;
                "pagination.pageSize"?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["quiz.v1.ListQuizResponse"];
                };
            };
        };
    };
    Quizzes_CreateQuiz: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["quiz.v1.CreateQuizRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["quiz.v1.CreateQuizResponse"];
                };
            };
        };
    };
    Quizzes_SearchQuiz: {
        parameters: {
            query?: {
                query?: string;
                "pagination.page"?: number;
                "pagination.pageSize"?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["quiz.v1.SearchQuizResponse"];
                };
            };
        };
    };
    Quizzes_GetQuiz: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["quiz.v1.GetQuizResponse"];
                };
            };
        };
    };
    Quizzes_DeleteQuiz: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["quiz.v1.DeleteQuizResponse"];
                };
            };
        };
    };
    Quizzes_UpdateQuiz: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["quiz.v1.UpdateQuizRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["quiz.v1.UpdateQuizResponse"];
                };
            };
        };
    };
    QuizQuestions_ListQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quizId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["quiz.v1.ListQuestionResponse"];
                };
            };
        };
    };
    QuizQuestions_AddQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quizId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["quiz.v1.AddQuestionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["quiz.v1.AddQuestionResponse"];
                };
            };
        };
    };
    QuizQuestions_DeleteQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quizId: string;
                questionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["quiz.v1.DeleteQuestionResponse"];
                };
            };
        };
    };
    QuizQuestions_UpdateQuestion: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quizId: string;
                questionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["quiz.v1.UpdateQuestionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["quiz.v1.UpdateQuestionResponse"];
                };
            };
        };
    };
    QuizAnswers_ValidateQuestionAnswers: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quizId: string;
                questionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["quiz.v1.ValidateQuestionAnswersRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["quiz.v1.ValidateQuestionAnswersResponse"];
                };
            };
        };
    };
    QuizAnswers_ListChoice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quizId: string;
                questionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["quiz.v1.ListChoiceResponse"];
                };
            };
        };
    };
    QuizAnswers_CreateChoice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quizId: string;
                questionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["quiz.v1.CreateChoiceRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["quiz.v1.CreateChoiceResponse"];
                };
            };
        };
    };
    QuizAnswers_DeleteChoice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quizId: string;
                questionId: string;
                choiceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["quiz.v1.DeleteChoiceResponse"];
                };
            };
        };
    };
    QuizAnswers_UpdateChoice: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                quizId: string;
                questionId: string;
                choiceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["quiz.v1.UpdateChoiceRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["quiz.v1.UpdateChoiceResponse"];
                };
            };
        };
    };
}
